import type { Priority, WorkItem, WorkItemType } from "@/lib/types";

const now = "2026-07-28T09:00:00.000Z";

/** Hand-authored items with real descriptions, links, and story detail. */
const authored: WorkItem[] = [
  {
    key: "ENG-4821",
    projectKey: "ENG",
    type: "story",
    title: "Inline edit work item title without a page reload",
    description:
      "The title field on the work item detail view should support click-to-edit with optimistic save. On blur, PATCH the field and roll back visually if the request fails, per FR-W02.",
    statusId: "eng-in-progress",
    assigneeId: "u2",
    reporterId: "u1",
    priority: "high",
    storyPoints: 5,
    labels: ["frontend", "detail-view"],
    sprintId: "sprint-eng-24",
    parentKey: null,
    epicKey: "ENG-4700",
    links: [{ type: "blocked-by", targetKey: "ENG-4831" }],
    createdAt: "2026-07-14T10:00:00.000Z",
    updatedAt: now,
    rank: 100,
  },
  {
    key: "ENG-4822",
    projectKey: "ENG",
    type: "subtask",
    title: "Wire optimistic update for the title field",
    description: "Client-side state updates immediately on submit; reconciles with server response.",
    statusId: "eng-done",
    assigneeId: "u2",
    reporterId: "u1",
    priority: "medium",
    storyPoints: 2,
    labels: [],
    sprintId: "sprint-eng-24",
    parentKey: "ENG-4821",
    epicKey: "ENG-4700",
    links: [],
    createdAt: "2026-07-15T10:00:00.000Z",
    updatedAt: now,
    rank: 101,
  },
  {
    key: "ENG-4823",
    projectKey: "ENG",
    type: "subtask",
    title: "Add rollback on save failure",
    description: "Revert the field to its last known-good value and surface a toast with a retry action.",
    statusId: "eng-in-progress",
    assigneeId: "u2",
    reporterId: "u1",
    priority: "medium",
    storyPoints: 1,
    labels: [],
    sprintId: "sprint-eng-24",
    parentKey: "ENG-4821",
    epicKey: "ENG-4700",
    links: [],
    createdAt: "2026-07-15T11:00:00.000Z",
    updatedAt: now,
    rank: 102,
  },
  {
    key: "ENG-4830",
    projectKey: "ENG",
    type: "story",
    title: "Sidebar field inline editing (assignee, priority, labels)",
    description:
      "Every sidebar field on the detail view opens its editor in place — no separate edit mode, no page reload. Assignee and labels support type-ahead search.",
    statusId: "eng-in-review",
    assigneeId: "u5",
    reporterId: "u1",
    priority: "medium",
    storyPoints: 8,
    labels: ["frontend", "detail-view"],
    sprintId: "sprint-eng-24",
    parentKey: null,
    epicKey: "ENG-4700",
    links: [],
    createdAt: "2026-07-14T12:00:00.000Z",
    updatedAt: now,
    rank: 103,
  },
  {
    key: "ENG-4831",
    projectKey: "ENG",
    type: "bug",
    title: "Description editor loses focus after autosave",
    description:
      "Typing in the description field, waiting for the 2s autosave debounce to fire, then continuing to type drops the cursor to the start of the field. Reproduces in Chrome and Firefox.",
    statusId: "eng-todo",
    assigneeId: "u1",
    reporterId: "u3",
    priority: "high",
    storyPoints: 2,
    labels: ["bug", "detail-view"],
    sprintId: "sprint-eng-24",
    parentKey: null,
    epicKey: "ENG-4700",
    links: [{ type: "blocks", targetKey: "ENG-4821" }],
    createdAt: "2026-07-20T09:00:00.000Z",
    updatedAt: now,
    rank: 104,
  },
  {
    key: "ENG-4790",
    projectKey: "ENG",
    type: "story",
    title: "Clickable filter token search bar",
    description:
      "Users build a query by clicking filter tokens (project, status, assignee, label) rather than learning query syntax, per FR-S01. Tokens render inline in the search bar and are individually removable.",
    statusId: "eng-in-progress",
    assigneeId: "u6",
    reporterId: "u1",
    priority: "high",
    storyPoints: 5,
    labels: ["frontend", "search"],
    sprintId: "sprint-eng-24",
    parentKey: null,
    epicKey: "ENG-4550",
    links: [],
    createdAt: "2026-07-13T09:00:00.000Z",
    updatedAt: now,
    rank: 105,
  },
  {
    key: "ENG-4791",
    projectKey: "ENG",
    type: "story",
    title: "JQL-compatible query autocomplete",
    description:
      "Power users can type a query directly in an independently-named, JQL-compatible syntax with live autocomplete for fields, operators, and values, per FR-S02.",
    statusId: "eng-todo",
    assigneeId: "u6",
    reporterId: "u1",
    priority: "medium",
    storyPoints: 8,
    labels: ["frontend", "search"],
    sprintId: "sprint-eng-24",
    parentKey: null,
    epicKey: "ENG-4550",
    links: [],
    createdAt: "2026-07-13T09:30:00.000Z",
    updatedAt: now,
    rank: 106,
  },
  {
    key: "ENG-4792",
    projectKey: "ENG",
    type: "task",
    title: "Saved views: share and subscribe to digest",
    description: "Any query can be saved as a named view, shared with a team, and subscribed to as a daily digest, per FR-S04.",
    statusId: "eng-todo",
    assigneeId: "u7",
    reporterId: "u1",
    priority: "low",
    storyPoints: 3,
    labels: ["search"],
    sprintId: "sprint-eng-24",
    parentKey: null,
    epicKey: "ENG-4550",
    links: [],
    createdAt: "2026-07-16T09:00:00.000Z",
    updatedAt: now,
    rank: 107,
  },
  {
    key: "ENG-4801",
    projectKey: "ENG",
    type: "bug",
    title: "Board column drag drops item behind the sticky header on Safari",
    description: "Dragging a card into the top slot of a column on Safari 18 places it visually behind the column header until scroll.",
    statusId: "eng-in-review",
    assigneeId: "u2",
    reporterId: "u3",
    priority: "urgent",
    storyPoints: 1,
    labels: ["bug", "board"],
    sprintId: "sprint-eng-24",
    parentKey: null,
    epicKey: null,
    links: [{ type: "relates-to", targetKey: "ENG-4790" }],
    createdAt: "2026-07-22T09:00:00.000Z",
    updatedAt: now,
    rank: 108,
  },
  {
    key: "ENG-4802",
    projectKey: "ENG",
    type: "task",
    title: "Command palette: recent items list",
    description: "⌘K opens with the user's five most recently viewed work items before any query is typed.",
    statusId: "eng-done",
    assigneeId: "u1",
    reporterId: "u1",
    priority: "low",
    storyPoints: 2,
    labels: ["frontend"],
    sprintId: "sprint-eng-24",
    parentKey: null,
    epicKey: null,
    links: [],
    createdAt: "2026-07-14T09:00:00.000Z",
    updatedAt: now,
    rank: 109,
  },
  {
    key: "ENG-4803",
    projectKey: "ENG",
    type: "story",
    title: "Sub-task aggregate progress indicator on parent card",
    description: "A story's board card and detail header show a fraction (e.g. 2/3) and a slim bar summarizing its sub-tasks' completion, per FR-W03.",
    statusId: "eng-done",
    assigneeId: "u5",
    reporterId: "u1",
    priority: "medium",
    storyPoints: 3,
    labels: ["frontend"],
    sprintId: "sprint-eng-24",
    parentKey: null,
    epicKey: "ENG-4700",
    links: [],
    createdAt: "2026-07-14T09:15:00.000Z",
    updatedAt: now,
    rank: 110,
  },
  {
    key: "ENG-4850",
    projectKey: "ENG",
    type: "story",
    title: "Typed links: Blocks / Relates to / Blocked by with live status",
    description: "Work items support typed links to other items with the target's live status visible inline, per FR-W04.",
    statusId: "eng-backlog",
    assigneeId: null,
    reporterId: "u1",
    priority: "medium",
    storyPoints: 5,
    labels: ["frontend", "detail-view"],
    sprintId: null,
    parentKey: null,
    epicKey: "ENG-4700",
    links: [],
    createdAt: "2026-07-10T09:00:00.000Z",
    updatedAt: now,
    rank: 200,
  },
  {
    key: "ENG-4851",
    projectKey: "ENG",
    type: "story",
    title: "Comment reactions",
    description: "Users can react to a comment with a small emoji set; reaction counts show inline below the comment.",
    statusId: "eng-backlog",
    assigneeId: null,
    reporterId: "u3",
    priority: "low",
    storyPoints: 2,
    labels: ["frontend"],
    sprintId: null,
    parentKey: null,
    epicKey: null,
    links: [],
    createdAt: "2026-07-10T09:10:00.000Z",
    updatedAt: now,
    rank: 201,
  },
  {
    key: "ENG-4852",
    projectKey: "ENG",
    type: "bug",
    title: "@mention autocomplete shows deactivated users",
    description: "The mention picker in comments should filter out users whose directory account is deactivated.",
    statusId: "eng-backlog",
    assigneeId: null,
    reporterId: "u3",
    priority: "medium",
    storyPoints: 1,
    labels: ["bug"],
    sprintId: null,
    parentKey: null,
    epicKey: null,
    links: [],
    createdAt: "2026-07-11T09:00:00.000Z",
    updatedAt: now,
    rank: 202,
  },
  {
    key: "ENG-4853",
    projectKey: "ENG",
    type: "task",
    title: "Legacy Jira URL redirect map (Class A migration prep)",
    description: "Build the lookup table mapping legacy Jira DC issue URLs to Strand equivalents ahead of migration, per FR-MG02.",
    statusId: "eng-backlog",
    assigneeId: null,
    reporterId: "u1",
    priority: "high",
    storyPoints: 5,
    labels: ["migration"],
    sprintId: null,
    parentKey: null,
    epicKey: null,
    links: [],
    createdAt: "2026-07-09T09:00:00.000Z",
    updatedAt: now,
    rank: 203,
  },
  {
    key: "ENG-4854",
    projectKey: "ENG",
    type: "story",
    title: "PII detection at content entry point",
    description: "Detect and block likely PII (e.g. account numbers) at the point of entry in titles, descriptions, and comments, per FR-W07.",
    statusId: "eng-backlog",
    assigneeId: null,
    reporterId: "u1",
    priority: "urgent",
    storyPoints: 8,
    labels: ["compliance"],
    sprintId: null,
    parentKey: null,
    epicKey: null,
    links: [],
    createdAt: "2026-07-08T09:00:00.000Z",
    updatedAt: now,
    rank: 204,
  },
  {
    key: "PLAT-1201",
    projectKey: "PLAT",
    type: "story",
    title: "Aurora outbox table and transactional write path",
    description: "Every mutation writes business state and a domain event to an outbox table within the same transaction, per §5.2.",
    statusId: "plat-in-progress",
    assigneeId: "u4",
    reporterId: "u4",
    priority: "high",
    storyPoints: 8,
    labels: ["backend", "spike"],
    sprintId: "sprint-plat-11",
    parentKey: null,
    epicKey: "PLAT-1200",
    links: [],
    createdAt: "2026-07-12T09:00:00.000Z",
    updatedAt: now,
    rank: 100,
    watcherIds: ["u1"],
  },
  {
    key: "PLAT-1202",
    projectKey: "PLAT",
    type: "task",
    title: "Provision MSK cluster and topics",
    description: "Stand up the Kafka (MSK) cluster and the topic set the outbox CDC pipeline will publish to.",
    statusId: "plat-in-progress",
    assigneeId: "u8",
    reporterId: "u4",
    priority: "high",
    storyPoints: 5,
    labels: ["infra"],
    sprintId: "sprint-plat-11",
    parentKey: null,
    epicKey: "PLAT-1200",
    links: [],
    createdAt: "2026-07-12T09:30:00.000Z",
    updatedAt: now,
    rank: 101,
  },
  {
    key: "PLAT-1203",
    projectKey: "PLAT",
    type: "task",
    title: "Debezium connector config for outbox CDC",
    description: "Configure the Debezium connector publishing the outbox table into the immutable, hash-chained event log.",
    statusId: "plat-todo",
    assigneeId: "u8",
    reporterId: "u4",
    priority: "medium",
    storyPoints: 5,
    labels: ["infra"],
    sprintId: "sprint-plat-11",
    parentKey: null,
    epicKey: "PLAT-1200",
    links: [],
    createdAt: "2026-07-13T09:00:00.000Z",
    updatedAt: now,
    rank: 102,
  },
  {
    key: "PLAT-1204",
    projectKey: "PLAT",
    type: "bug",
    title: "Aurora Global Database replica lag alert misfires",
    description: "The replica-lag alarm fires false positives during routine snapshot windows; needs a smarter threshold.",
    statusId: "plat-blocked",
    assigneeId: "u4",
    reporterId: "u8",
    priority: "high",
    storyPoints: 2,
    labels: ["bug", "infra"],
    sprintId: "sprint-plat-11",
    parentKey: null,
    epicKey: null,
    links: [{ type: "blocks", targetKey: "PLAT-1201" }],
    createdAt: "2026-07-21T09:00:00.000Z",
    updatedAt: now,
    rank: 103,
  },
  {
    key: "PLAT-1205",
    projectKey: "PLAT",
    type: "task",
    title: "IAM roles for EKS service accounts",
    description: "Least-privilege IAM roles for each core module's service account, mapped via IRSA.",
    statusId: "plat-done",
    assigneeId: "u8",
    reporterId: "u4",
    priority: "medium",
    storyPoints: 3,
    labels: ["infra", "security"],
    sprintId: "sprint-plat-11",
    parentKey: null,
    epicKey: null,
    links: [],
    createdAt: "2026-07-12T10:00:00.000Z",
    updatedAt: now,
    rank: 104,
  },
  {
    key: "PLAT-1220",
    projectKey: "PLAT",
    type: "story",
    title: "Zero-downtime reindex validation spike",
    description: "One of the six mandatory Tier-0 validation spikes: prove zero-downtime reindex time from the event log, per §5.3.",
    statusId: "plat-backlog",
    assigneeId: null,
    reporterId: "u4",
    priority: "high",
    storyPoints: 8,
    labels: ["spike"],
    sprintId: null,
    parentKey: null,
    epicKey: null,
    links: [],
    createdAt: "2026-07-05T09:00:00.000Z",
    updatedAt: now,
    rank: 200,
    watcherIds: ["u1"],
  },
  {
    key: "PLAT-1221",
    projectKey: "PLAT",
    type: "task",
    title: "Permission-check performance benchmark at 25k concurrent",
    description: "Load-test the authorization hot path at 25,000 simulated concurrent users, per §5.3.",
    statusId: "plat-backlog",
    assigneeId: null,
    reporterId: "u4",
    priority: "urgent",
    storyPoints: 8,
    labels: ["spike", "performance"],
    sprintId: null,
    parentKey: null,
    epicKey: null,
    links: [],
    createdAt: "2026-07-05T09:30:00.000Z",
    updatedAt: now,
    rank: 201,
  },
  {
    key: "PLAT-1222",
    projectKey: "PLAT",
    type: "bug",
    title: "EFS index snapshot cleanup cron leaves orphaned files",
    description: "The legacy Jira DC EFS snapshot cleanup job occasionally leaves orphaned index files, inflating storage costs.",
    statusId: "plat-backlog",
    assigneeId: null,
    reporterId: "u8",
    priority: "low",
    storyPoints: 1,
    labels: ["bug", "infra"],
    sprintId: null,
    parentKey: null,
    epicKey: null,
    links: [],
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: now,
    rank: 202,
  },
];

/** Deterministic filler so the backlog view has real scroll depth for bulk-select and quick-create testing. */
const fillerTitles = [
  "Add empty state illustration",
  "Tighten focus ring contrast",
  "Paginate audit log query",
  "Cache workflow status lookups",
  "Handle null assignee in board card",
  "Add keyboard shortcut cheat sheet",
  "Debounce backlog search input",
  "Fix label chip overflow at narrow width",
  "Add loading skeleton for board columns",
  "Support tab-to-column-header navigation",
  "Trim trailing whitespace on save",
  "Add unit tests for rank re-ordering",
];
const fillerTypes: WorkItemType[] = ["task", "bug", "story"];
const fillerPriorities: Priority[] = ["low", "medium", "high"];
const fillerReporters = ["u1", "u3", "u4", "u7"];

function buildFiller(projectKey: "ENG" | "PLAT", backlogStatusId: string, count: number, startNumber: number): WorkItem[] {
  return Array.from({ length: count }, (_, i) => {
    const n = startNumber + i;
    const title = fillerTitles[i % fillerTitles.length];
    return {
      key: `${projectKey}-${n}`,
      projectKey,
      type: fillerTypes[i % fillerTypes.length],
      title,
      description: `${title}. Filed from backlog grooming.`,
      statusId: backlogStatusId,
      assigneeId: null,
      reporterId: fillerReporters[i % fillerReporters.length],
      priority: fillerPriorities[i % fillerPriorities.length],
      storyPoints: [1, 2, 3, 5][i % 4],
      labels: [],
      sprintId: null,
      parentKey: null,
      epicKey: null,
      links: [],
      createdAt: "2026-06-01T09:00:00.000Z",
      updatedAt: now,
      rank: 300 + i,
    };
  });
}

export const issues: WorkItem[] = [
  ...authored,
  ...buildFiller("ENG", "eng-backlog", 18, 4900),
  ...buildFiller("PLAT", "plat-backlog", 12, 1300),
];

export function getIssue(key: string): WorkItem | undefined {
  return issues.find((i) => i.key === key);
}

export function getIssuesByProject(projectKey: string): WorkItem[] {
  return issues.filter((i) => i.projectKey === projectKey);
}

export function getSubtasks(parentKey: string): WorkItem[] {
  return issues.filter((i) => i.parentKey === parentKey);
}

export function getSprintIssues(sprintId: string): WorkItem[] {
  return issues.filter((i) => i.sprintId === sprintId);
}

export function getBacklogIssues(projectKey: string): WorkItem[] {
  return issues
    .filter((i) => i.projectKey === projectKey && i.sprintId === null && i.parentKey === null)
    .sort((a, b) => a.rank - b.rank);
}
